name: 'ParkHub Update Integration Test Badge'
description: 'Update badge in README to read in current branch'
inputs:
  repo:
    description: 'Name of the repo.'
    required: true
    default: ${{ github.repo }}
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   args:
#     - ${{ inputs.repo }}
runs:
  using: "composite"
  steps: 
    - run: ls
      shell: bash
    - run: $/run.sh
      shell: bash